# Generated by Django 4.1.7 on 2023-08-17 16:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_drink',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_toppings',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
