# Generated by Django 4.1.7 on 2023-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_sold',
            field=models.IntegerField(default=0),
        ),
    ]
